/**
 * 專案列表。
 *
 * 包含各個專案的詳細資訊，如圖片、連結、名稱和技術標籤。
 */
export const PROJECT_LIST = [
    {
        id: 'taipei-beef-noodles-rank',
        image: '/projects/taipei-beef-noodles-rank.jpg',
        url: 'https://taipei-beef-noodles-rank.garylin.dev',
        name: '北市牛肉麵排行榜',
        tags: [
            '2025',
            'Google Places API(New)',
            'React.js',
            'TypeScript',
            'Tailwind CSS',
            'Shadcn UI',
            'TanStack Query',
        ],
    },
    {
        id: 'hot-now',
        image: '/projects/hot-now.jpg',
        url: 'https://hotnow.garylin.dev',
        name: 'Hot Now｜熱門話題一把抓',
        tags: [
            '2025',
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Shadcn UI',
            'Zustand',
            'TanStack Query',
            'React Hook Form',
            'Zod',
            'Google Analytics',
            'Puppeteer',
            'next-themes',
        ],
    },
    {
        id: 'gary-line-bot',
        image: '/projects/gary-line-bot.jpg',
        url: 'https://github.com/garylin0969/gary-line-bot',
        name: 'LINE機器人 - 蓋瑞爸爸大俠',
        tags: ['2025', 'TypeScript', 'LINE', 'Wrangler', 'OpenCC'],
    },
    {
        id: 'life-restart',
        image: '/projects/life-restart.jpg',
        url: 'https://life-restart.garylin.dev',
        name: '人生重來 - Life Restart',
        tags: ['2025', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Shadcn UI', 'next-intl', 'next-themes'],
    },
    {
        id: 'perplexity-concat',
        image: '/projects/perplexity-concat.jpg',
        url: 'https://perplexity-concat.garylin.dev',
        name: 'AI 串接測試工具 - Perplexity AI Concat',
        tags: [
            '2025',
            'Perplexity API',
            'React.js',
            'TypeScript',
            'Tailwind CSS',
            'React Hook Form',
            'React Json View',
        ],
    },
    {
        id: 'gemini-tester',
        image: '/projects/gemini-tester.jpg',
        url: 'https://gemini-tester.garylin.dev',
        name: 'AI 串接測試工具 - Gemini API Tester',
        tags: ['2025', 'Gemini', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Shadcn UI', 'React Query'],
    },
    {
        id: 'garylin-dev',
        image: '/projects/garylin-dev.jpg',
        url: 'https://github.com/garylin0969/garylin.dev',
        name: 'personal website - garylin.dev',
        tags: ['2024', 'Next.js', 'TypeScript', 'Google Analytics', 'Velite', 'Tailwind CSS', 'next-themes', 'Giscus'],
    },
    {
        id: 'chinese-number-format',
        image: '/projects/chinese-number-format.avif',
        url: 'https://www.npmjs.com/package/chinese-number-format',
        name: 'NPM 套件 - chinese-number-format',
        tags: ['2024', 'TypeScript', 'Jest', 'NPM'],
    },
    {
        id: 'imdb-clone',
        image: '/projects/imdb-clone.avif',
        url: 'https://imdb-clone.garylin.dev',
        name: 'Clone - IMDb',
        tags: ['2023', 'Next.js', 'TypeScript', 'React Hook Form', 'SWR', 'Tailwind CSS', 'next-themes'],
    },
    {
        id: 'google-clone',
        image: '/projects/google-clone.avif',
        url: 'https://google-clone.garylin.dev',
        name: 'Clone - Google',
        tags: ['2023', 'Next.js', 'TypeScript', 'React Hook Form', 'SWR', 'Tailwind CSS'],
    },
    {
        id: 'akatsuki',
        image: '/projects/akatsuki.avif',
        url: 'https://akatsuki.garylin.dev',
        name: '火影忍者 - 曉組織成員介紹',
        tags: ['2023', 'React.js', 'Redux', 'TypeScript', 'Styled Components'],
    },
    {
        id: 'ispan-project',
        image: '/projects/ispan-project.jpg',
        url: 'https://github.com/garylin0969/react-ispan-project',
        name: 'iSpan 資策會 - 專題',
        tags: ['2022', 'React.js', 'JavaScript', 'Socket.IO', 'Bootstrap', 'GSAP'],
    },
];
